version: '3.1'

services:
  database:
    image: mysql:8
    #docker run -p 3306:3306 --name mysql -e MYSQL_ROOT_HOST=% -e MYSQL_ROOT_PASSWORD=system -e MYSQL_DATABASE=myorg -e MYSQL_USER=me -e MYSQL_PASSWORD=system -d mysql:5.7
    ports: 
      - 3300:3306
    environment:
      - 'MYSQL_ROOT_HOST=%'
      - 'MYSQL_ROOT_PASSWORD=prueba'
      - 'MYSQL_DATABASE=schema'
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=password'

  demo:
    image: demo:latest
    ports:
      - 8080:8080
